apiVersion: v1
kind: Namespace
metadata:
  name: digitrans-cm
  labels:
    name: digitrans-cm
    project: DIGITRANS-CM
    client: AGROCAM-SA
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: digitrans-cm-config
  namespace: digitrans-cm
data:
  REDIS_HOST: "redis-service.digitrans-cm.svc.cluster.local"
  REDIS_PORT: "6379"
  RABBITMQ_HOST: "rabbitmq-service.digitrans-cm.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  AWS_REGION: "af-south-1"
  ENVIRONMENT: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: digitrans-cm-secrets
  namespace: digitrans-cm
type: Opaque
stringData:
  JWT_SECRET: "agrocam-digitrans-secret-key-2024-very-long-secret"
  DB_USER: "admin"
  DB_PASS: ""
  RABBITMQ_PASS: "guest"
